### ISSUE TITLE
Stranges outputs for most_used_templates

### ISSUE THREAD

**Issue by framawiki** [Niharika29/database-reports#6]
Script add ghost templates on the [most_used_templates list](https://fr.wikipedia.org/w/index.php?title=Wikip%C3%A9dia:Rapports/Modeles_inclus_sur_le_plus_grand_nombre_de_pages&diff=prev&oldid=129251483). Theses templates has never been created.
Thanks you.

**Comment by framawiki** [comment]
Same for [talk_pages_by_size](https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Rapports/Pages_de_discussion_par_taille), the report seems outdated

**Comment by Niharika29** [comment]
Okay, this was a fun investigation. Turns out French wiki has two separate namespaces (10 and 828) for templates. So the missing templates are at Module:<template-name> and not Modèle:<template-name>.
For example: https://fr.wikipedia.org/wiki/Module:Coordinates and https://fr.wikipedia.org/wiki/Module:Outils

My code doesn't support this yet but it should be pretty straightforward because we can get tl_namespace along with tl_title and then specify the namespace name based on that. Maybe we can even get away with using the namespace number instead of using the namespace name. 

Thanks for reporting.

**Comment by kaldari** [comment]
The Module namespace is for Lua Modules, not Templates. This is the same across all wikis. You probably just need to exclude namespace 828 from the queries.

**Comment by Niharika29** [comment]
The original query that was used to update the page included both 10 and 828. I can exclude it from my query though. Maybe we can have a separate report for Lua modules if someone asks for it.

**Comment by Niharika29** [comment]
Done.

**Comment by framawiki** [comment]
Thanks you.
